[package]
name = "topfew"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
edition = "2018"

[dependencies]
anyhow = "1"
err-derive = "0.2.4"
regex = "1"
structopt = "0.3"

[profile.release]
codegen-units = 1
opt-level = 3
debug = true
